const sampleJobs = [
  {
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Toronto, ON",
    jobType: "Full-Time",
    workMode: "Hybrid",
    experienceLevel: "Entry",
    salary: 65000,
    description:
      "Build responsive web applications using React, HTML, CSS, and Bootstrap.",
    skills: ["JavaScript", "React", "HTML", "CSS", "Bootstrap"],
    postedAt: new Date("2026-01-15"),
  },
  {
    title: "Backend Developer",
    company: "InnovateX",
    location: "Vaughan, ON",
    jobType: "Full-Time",
    workMode: "Onsite",
    experienceLevel: "Mid",
    salary: 80000,
    description:
      "Develop REST APIs and manage MongoDB databases using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
    postedAt: new Date("2026-01-20"),
  },
  {
    title: "Technical Sales Specialist",
    company: "NTT BPO",
    location: "Remote",
    jobType: "Full-Time",
    workMode: "Remote",
    experienceLevel: "Mid",
    salary: 60000,
    description:
      "Manage client communications, handle outbound sales, and maintain CRM data.",
    skills: ["Sales", "CRM", "Communication"],
    postedAt: new Date("2026-02-01"),
  },
  {
    title: "UI/UX Designer",
    company: "Creative Solutions",
    location: "Mississauga, ON",
    jobType: "Contract",
    workMode: "Hybrid",
    experienceLevel: "Mid",
    salary: 70000,
    description:
      "Design user interfaces and improve user experience for web and mobile apps.",
    skills: ["Figma", "UI Design", "UX Research", "Prototyping"],
    postedAt: new Date("2026-01-18"),
  },
  {
    title: "Data Analyst",
    company: "DataSense",
    location: "Toronto, ON",
    jobType: "Full-Time",
    workMode: "Onsite",
    experienceLevel: "Entry",
    salary: 68000,
    description:
      "Analyze business data using SQL, Excel, and Python to generate insights.",
    skills: ["SQL", "Excel", "Python", "Data Visualization"],
    postedAt: new Date("2026-01-25"),
  },
  {
    title: "Full Stack Developer",
    company: "NextGen Tech",
    location: "Brampton, ON",
    jobType: "Full-Time",
    workMode: "Hybrid",
    experienceLevel: "Mid",
    salary: 90000,
    description:
      "Work on both frontend and backend tasks using MERN stack technologies.",
    skills: ["MongoDB", "Express", "React", "Node.js"],
    postedAt: new Date("2026-02-03"),
  },
  {
    title: "Marketing Coordinator",
    company: "Bright Minds",
    location: "Oakville, ON",
    jobType: "Part-Time",
    workMode: "Onsite",
    experienceLevel: "Entry",
    salary: 50000,
    description:
      "Assist in digital marketing campaigns, social media management, and SEO.",
    skills: ["SEO", "Social Media", "Content Creation"],
    postedAt: new Date("2026-01-22"),
  },
  {
    title: "DevOps Engineer",
    company: "CloudWave",
    location: "Toronto, ON",
    jobType: "Full-Time",
    workMode: "Remote",
    experienceLevel: "Senior",
    salary: 110000,
    description:
      "Implement CI/CD pipelines and manage cloud infrastructure on AWS.",
    skills: ["AWS", "Docker", "CI/CD", "Kubernetes"],
    postedAt: new Date("2026-01-30"),
  },
  {
    title: "Customer Support Representative",
    company: "HelpDesk Pro",
    location: "Remote",
    jobType: "Full-Time",
    workMode: "Remote",
    experienceLevel: "Entry",
    salary: 45000,
    description:
      "Handle customer queries, provide technical support, and manage tickets.",
    skills: ["Customer Service", "Technical Support", "Ticketing Systems"],
    postedAt: new Date("2026-01-28"),
  },
  {
    title: "Project Manager",
    company: "BuildSmart",
    location: "Vaughan, ON",
    jobType: "Full-Time",
    workMode: "Hybrid",
    experienceLevel: "Senior",
    salary: 100000,
    description:
      "Oversee software development projects, manage timelines, and coordinate teams.",
    skills: ["Agile", "Scrum", "Team Leadership", "Project Planning"],
    postedAt: new Date("2026-02-05"),
  },
];

module.exports = { data: sampleJobs };
